apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 975050175231.dkr.ecr.eu-central-1.amazonaws.com/java-app:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name:
              key:
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name:
              key:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name:
              key:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name:
              key:
              
